### ISSUE TITLE
Mismatched anonymous define() module

### ISSUE THREAD

**Issue by ghost** [Famous/famous-angular#160]
Hi,
I installed famous-angular as it's described here: https://github.com/Famous/famous-angular 

I can see 'Hello World' on the red background, but there are two JavaScript errors:

```
Uncaught Error: Mismatched anonymous define() module: function (){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw ne...<omitted>...ch require.js:166
Uncaught Error: Mismatched anonymous define() module: [object Object]
```

And sometimes when I refresh the page I cannot even see 'Hello World' on the red background, because I get these errors:

```
Uncaught Error: Mismatched anonymous define() module: function (){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw ne...<omitted>...ch require.js:166
TypeError: object is not a function
    at Object.createContext (http://localhost:5000/bower_components/famous/core/Engine.js:277:23)
    at pre (http://localhost:5000/bower_components/famous-angular/dist/famous-angular.js:1505:38)
    at nodeLinkFn (http://localhost:5000/bower_components/angular/angular.js:6330:13)
    at compositeLinkFn (http://localhost:5000/bower_components/angular/angular.js:5757:15)
    at compositeLinkFn (http://localhost:5000/bower_components/angular/angular.js:5764:13)
    at compositeLinkFn (http://localhost:5000/bower_components/angular/angular.js:5764:13)
    at publicLinkFn (http://localhost:5000/bower_components/angular/angular.js:5666:30)
    at link (http://localhost:5000/bower_components/angular-route/angular-route.js:921:7)
    at nodeLinkFn (http://localhost:5000/bower_components/angular/angular.js:6350:13)
    at compositeLinkFn (http://localhost:5000/bower_components/angular/angular.js:5761:15) <fa-app style="height: 200px" class="ng-scope"> 
```

Do you think you can help me? Thanks.

**Comment by praWeb** [comment]
i want to use requirejs and to resolve this issue. can some one help me on this
