### ISSUE TITLE
Error when removing element in combination with pipe-to

### ISSUE THREAD

**Issue by janober** [Famous/famous-angular#185]
Sorry have again a pipeing issue.

When I diplay multiple items with ng-repeat and then remove one, I get the following error message:
```
TypeError: undefined is not a function
    at bulkUpdatePipes (http://127.0.0.1/famous-angular-examples/app/bower_components/famous-angular/dist/famous-angular.js:732:31)
    at unpipesFromTargets (http://127.0.0.1/famous-angular-examples/app/bower_components/famous-angular/dist/famous-angular.js:748:7)
    at http://127.0.0.1/famous-angular-examples/app/bower_components/famous-angular/dist/famous-angular.js:4202:27
    at Scope.$broadcast (http://127.0.0.1/famous-angular-examples/app/bower_components/angular/angular.js:12937:28)
    at Scope.$destroy (http://127.0.0.1/famous-angular-examples/app/bower_components/angular/angular.js:12595:14)
    at ngRepeatAction (http://127.0.0.1/famous-angular-examples/app/bower_components/angular/angular.js:20493:27)
...
```
This only happens when I use "fa-pipe-to" on the draggable. I tried to unpipe manually before removing the item but got the same. But not sure if I did it correctly. Would be great to get a tipp how to avoid that and implement that correctly. Thanks!

The example bellow is on the basis of the draggable famous-angular-example. 

JavaScript Code:
```
angular.module('integrationApp')
  .controller('TestCtrl', function ($scope, $famous) {
    var EventHandler = $famous['famous/core/EventHandler'];

    var data = [];
    data.push( {id: 0, name: 'zero', position: [10, 100], handler: new EventHandler() } );
    data.push( {id: 1, name: 'one',  position: [10, 200], handler: new EventHandler() } );
    data.push( {id: 2, name: 'two',  position: [10, 300], handler: new EventHandler() } );

    $scope.nodes = data;

    $scope.remove = function() {
      delete $scope.nodes[1];
      console.log($scope.nodes);
    }

  });
```

HTML Code:
```
<fa-app style="width: 320px; height: 568px; overflow: hidden;">
    <fa-modifier ng-repeat="node in nodes"  fa-translate="[10,500]" fa-size="[80, 40]">
        <fa-surface>
          <button ng-click="remove()">Remove one</button>
      </fa-surface>
    </fa-modifier>

  <fa-modifier ng-repeat="node in nodes"  fa-translate="node.position" fa-size="[80, 40]">
    <fa-draggable fa-pipe-from="node.handler" fa-pipe-to="node.handler">
      <fa-surface fa-background-color="'red'" fa-size="[undefined, undefined]" fa-pipe-to="node.handler">
        {{node.id}}: {{node.name}}
      </fa-surface>
    </fa-draggable>
  </fa-modifier>

</fa-app>
```

**Comment by jordanpapaleo** [comment]
@janober Is this still a valid issue?  Thanks - Jordan

**Comment by janober** [comment]
Very sorry. Was working on another project the last months, so did not really check back here. I am actually just starting with this now again.

First, thanks a lot for everybody who worked on it! I just tested and it works fine now. So close it.
