### ISSUE TITLE
Problem with loading famous-angular with meteor (using meteor-bower)

### ISSUE THREAD

**Issue by vivekkatta** [Famous/famous-angular#356]
Hi, I am using meteor 1.1.0.2. Today I installed meteor-bower and gave a bower.json file without any dependencies in it (as suggested in your readme.md). While starting meteor, I get the following error:

```
=> Started proxy.                             
=> Started MongoDB.                           
Bower:  famous-angular v0.5.2 successfully installed
Bower:  famous-angular-bower vundefined successfully installed
Bower:  angular v1.3.8 successfully installed
Bower:  famous v0.3.4 successfully installed
=> Errors prevented startup:                  
   
   While building the application:
   fs.js:488:19: EISDIR, illegal operation on a directory (compiling lib/bower/bower.json)
   at Object.fs.readSync (fs.js:488:19)
   at Object.fs.readSync
   (/Users/vivekkatta/.meteor/packages/mquandalle_bower/.1.3.12_3.11zq6tl++os+web.browser+web.cordova/plugin.bower.os/npm/bower/node_modules/bower/node_modules/bower-config/node_modules/graceful-fs/polyfills.js:218:23)
   at Object.fs.readSync
   (/Users/vivekkatta/.meteor/packages/mquandalle_bower/.1.3.12_3.11zq6tl++os+web.browser+web.cordova/plugin.bower.os/npm/bower/node_modules/bower/node_modules/bower-registry-client/node_modules/graceful-fs/polyfills.js:218:23)
   at Object.fs.readSync
   (/Users/vivekkatta/.meteor/packages/mquandalle_bower/.1.3.12_3.11zq6tl++os+web.browser+web.cordova/plugin.bower.os/npm/bower/node_modules/bower/node_modules/bower-json/node_modules/graceful-fs/polyfills.js:218:23)
   at Object.fs.readFileSync (fs.js:322:28)
   at packages/bower/plugin/handler.js:122:1
   at Array.forEach (native)
   at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
   at packages/bower/plugin/handler.js:119:1
   at Array.forEach (native)
   at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
   at bowerHandler (packages/bower/plugin/handler.js:83:1)
   at Package (packages/bower/plugin/handler.js:225:1)
   
   
=> Your application has errors. Waiting for file change.
```

Bower file I am using:

```
{
  "name": "test-bower",
  "version": "0.0.1",
  "dependencies": {
       "famous-angular": "0.5.2"
  }
}
```

Steps to reproduce this error:

1) Install meteor
2) Create a meteor project using `meteor create test-bower`
3) Install the meteor-bower package using `meteor add mquandalle:bower`
4) Create the above bower.json file in <project-root>/lib/bower directory
5) Start application using `meteor`

Appreciate your help with this. Thanks!

Best,
Vivek

**Comment by idanwe** [comment]
I suggest you to use the `sgi:famous-angular` meteor package instead, I work it.

And with `urigo:angular` for the angular meteor integration.

**Comment by vivekkatta** [comment]
I did use sgi:famous-angular. But that package includes an older version of urigo:angular although I installed the latest urigo:angular separately.
